name: Build Ansible Collection
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2
      - run: |
          ansible --version
      - run: |
          python3 -m pip install ansible-lint
          ansible-lint --version
