name: Build Ansible Collection
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2
      # Retrieving variables from galaxy.yml
      - run: |
          ansible --version
          echo "COLLECTION_NAMESPACE=`grep 'namespace:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`" >> $GITHUB_ENV
          echo "COLLECTION_NAME=`grep 'name:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`" >> $GITHUB_ENV
          echo "VERSION=`grep 'version:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`" >> $GITHUB_ENV
      # Printing variables
      - run: |
          echo $COLLECTION_NAMESPACE
          echo $COLLECTION_NAME
          echo $VERSION
      # Building collection
      - run: |
          ansible-galaxy collection build
      # Upload generated tar file as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: $COLLECTION_NAMESPACE-$COLLECTION_NAME-$VERSION-${{ env.repo_hash }}
          path: |
            ${{ github.workspace }}/**/*.tar.gz
  
      
